services:
  app:
    build:
      context: .
      args:
        dev: "true" # Lowercase key to match ARG in Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

